name: CI/CD Pipeline

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read

env:
  CI_OTP_VERSION: "27.0"
  CI_GLEAM_VERSION: 1.2.1
  CI_REBAR3_VERSION: "3"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
      - name: Install npm packages
        run: npm ci
      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlintrc.json
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up BEAM dependencies
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.CI_OTP_VERSION }}
          gleam-version: ${{ env.CI_GLEAM_VERSION }}
          rebar3-version: ${{ env.CI_REBAR3_VERSION }}
      - name: Install Gleam packages
        run: gleam deps download
      - name: Run tests
        run: gleam test
  publish:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up BEAM dependencies
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.CI_OTP_VERSION }}
          gleam-version: ${{ env.CI_GLEAM_VERSION }}
          rebar3-version: ${{ env.CI_REBAR3_VERSION }}
      - name: Publish Hex package
        env:
          HEXPM_API_KEY: ${{ secrets.HEXPM_API_KEY }}
        run: gleam publish -y
